x-superset-depends-on: &superset-depends-on
  - db
  - redis
x-superset-volumes:
  &superset-volumes # /app/pythonpath_docker will be appended to the PYTHONPATH in the final container
  - ./docker:/app/docker
  - superset_home:/app/superset_home

x-common-build: &common-build
  context: .
  target: dev
  cache_from:
    - apache/superset-cache:3.10-slim-bookworm

version: "4.0"
services:
  redis:
    image: redis:7
    container_name: superset_cache
    restart: unless-stopped
    volumes:
      - redis:/data
    networks:
      - external_network

  db:
    env_file: .env
    image: postgres:15
    container_name: superset_db
    restart: unless-stopped
    volumes:
      - ${SUPERSET_DB_VOLUME:-db_home}:/var/lib/postgresql/data
      # - ./docker/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    networks:
      - external_network

  superset:
    env_file: .env
    build:
      <<: *common-build
    container_name: superset_app
    command: ["/app/docker/docker-bootstrap.sh", "app-gunicorn"]
    user: "root"
    restart: unless-stopped
    ports:
      - ${SUPERSET_PORT:-8088}:8088
    depends_on: *superset-depends-on
    volumes: *superset-volumes
    networks:
      - external_network

  superset-init:
    container_name: superset_init
    build:
      <<: *common-build
    command: ["/app/docker/docker-init.sh"]
    env_file: .env
    depends_on: *superset-depends-on
    user: "root"
    volumes: *superset-volumes
    healthcheck:
      disable: true
    networks:
      - external_network

  superset-worker:
    build:
      <<: *common-build
    container_name: superset_worker
    command: ["/app/docker/docker-bootstrap.sh", "worker"]
    env_file: .env
    restart: unless-stopped
    depends_on: *superset-depends-on
    user: "root"
    volumes: *superset-volumes
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "celery -A superset.tasks.celery_app:app inspect ping -d celery@$$HOSTNAME",
        ]
    networks:
      - external_network

  superset-worker-beat:
    build:
      <<: *common-build
    container_name: superset_worker_beat
    command: ["/app/docker/docker-bootstrap.sh", "beat"]
    env_file: .env
    restart: unless-stopped
    depends_on: *superset-depends-on
    user: "root"
    volumes: *superset-volumes
    networks:
      - external_network
    healthcheck:
      disable: true

networks:
  external_network:
    name: ${SUPERSET_DOCKER_NETWORK:-portal-production-network}
    external: true

volumes:
  superset_home:
    external: false
  db_home:
    external: false
  redis:
    external: false
